#!/bin/bash
# prerm script for evolution-translate-extension
# Cleanup before package removal

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # No process manipulation here. If Evolution is running during removal or upgrade,
        # the user may need to restart it to unload/reload modules.
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac


exit 0
